### ISSUE TITLE
Объединить VR для всех стран

### ISSUE THREAD

**Issue by rechkalov** [2gis/nuclear-river-validation-rules#294]
Делает ненужным #199

**Comment by rechkalov** [comment]
### Единичные проверки
* Как хранить все строки подключения к Erm?
* Как выбирать нужную базу Erm?

**Comment by rechkalov** [comment]
### Репликация
* Как организовать потоки?
  * Читать события из разных топиков SB, ходить в соответствующие базы
  * Или складывать события в один топик, затем какой-то магией определять базу.
* Будут ли конфликты по идентификаторам? 
  * Как отличить пересечение от конфликта? 
  * Можно ли выбрать одну из инсталляций Erm мастер-системой?
* Требуются ли изменения в версионировании проверок?

**Comment by rechkalov** [comment]
### Инициализация
* Как хранить все строки подключения к Erm?
* Будут ли конфликты по идентификаторам?
* Как сократить время простоя?

**Comment by rechkalov** [comment]
### Запросы
* Как получать имена сущностей для нужной локализации?

**Comment by maximpashuk** [comment]
Объединили
