### ISSUE TITLE
Implement ValidationResult statuses

### ISSUE THREAD

**Issue by denisivan0v** [2gis/nuclear-river-validation-rules#3]
Проблема: сейчас в зависимости от контекста вызова проверки критичность её срабатывания может различаться.

Согласно https://confluence.2gis.ru/pages/viewpage.action?pageId=51577357 есть 4 контекста проверок, каждая проверка для каждого контекста может выдавать 3 различных результата. 
Итого, возможен 81 вариант, не так уж много. Значит, вполне подойдёт решение с целочисленным полем статуса, который будет интерпретироваться Querying **со знанием контекста** проверки (отсюда требование передавать не только ключ для поиска сообщений - период, город, и т. п., но и контекст, в котором запрашиваются результаты.

Кроме того, **как правило**, одна проверка может выдавать только одну комбинацию. Есть исключения, например LinkingObjectsOrderValidationRule выдаёт Warning при единичной и Error при массовых, за исключением случаев, когда проверятся позиция с типом объекта привязки CategoryMultipleAsterix - тогда уровень Info. Это усложняет проверку и может служить формальным поводом разбить её на два независимых ValidationResult - проблемой является только то, что выборка и критерии запуска обоих полученных проверок будет абсолютно одинаковой, отличие будет лишь в одном условии.

Если всё-таки принять утверждение "одна проверка может иметь только один статус" то достаточно будет сопоставления проверок и их статусов, причём это сопоставление может быть изменено без перезапуска репликации. Вопрос, нужно ли это.

Можно положить расшифровку этих статусов прямо в таблицу вида 

| Status | Single | Mass | MassPrerelease | MassRelease |
| --- | --- | --- | --- | --- |
| ... |  |  |  |  |
| 57 | Error | Info | Waring | Info |
| ... |  |  |  |  |

Можно не заморачиваться с этим, статус 57 можно прочитать в троичной системе (2010), что в свою очередь легко мапится на Single = Error, Mass = Info, MassPrerelease = Waring, MassRelease = Info.

**Comment by rechkalov** [comment]
Сделано иначе: у каждой проверки фиксированный набор статусов, в зависимости от режима обращения - для репликации эти статусы не существенны, присутствуют только в Querying в виде реестра по проверкам (в коде).
