### ISSUE TITLE
Релиз всегда пересоздаёт подписки

### ISSUE THREAD

**Issue by rechkalov** [2gis/nuclear-river-validation-rules#317]
В результате чего теряются сообщения, результаты становятся некорректными, сейчас будет корректным только релиз с переинициализацией всех схем.

**Comment by maximpashuk** [comment]
В сборке декабря 2017 года это сыграло.

Мы фиксили срочный баг по балансам, я забыл об этом нюансе, и мы развернули хотфикс и пересоздали подписки, тем самым потеряв несколько сообщений.

В ночном запуске было видно что есть небольшая рассинхронизация по табличкам, я посчитал это несущественным.

Но нет, таки это сыграло и возник ещё один блокер сборки, который легко лечится передёргиванием , но всё же неприятен.
Поэтому предлагаю не затягивать с этим багом.
