### ISSUE TITLE
Переделать проверку "AMS жив"

### ISSUE THREAD

**Issue by maximpashuk** [2gis/nuclear-river-validation-rules#331]
Сейчас проверка "AMS жив" основана на времени - если текущее время VR и время последнего сообщения в kafka расходятся более чем на epsilon, то считается что "AMS мёртв" и для всех проверок формируется блокирующая ошибка.

К сожалению, такая проверка подвержена проблеме "расхождения времени".
Если часы на сервере AMS и время VR не синхронизованы, то возможны проблемы - ложная блокирующая ошибка "AMS мёртв" хотя AMS на самом деле не мётрв а просто разошлось время на серверах более чем на epsilon.

Можно попробовать поменять алгоритм проверки с сохранением функциональности.
Например: сохранять offset последнего сообщения между запусками job в VR - проверять что если offset не меняется несколько раз, то уже тогда бить тревогу - в этом алгоритме мы отвяжемся от синхронизации по времени.

**Comment by rechkalov** [comment]
Не поможет - в ситуации, когда ams выдаёт сообщения медленно и с отставанием (такие ситуации, как я помню, повторялись неоднократно) возникнет ложное ощущение, что всё в порядке.

**Comment by maximpashuk** [comment]
Согласен, тогда единственное что можно это ослабить немного интервал.
Сейчас он всего 20 секунд - если в kafka 20 секунд AMS ничего не писал то мы бьём тревогу.
Аналогично если время AMS и VR разошлось на 20 секунд то мы бьём тревогу.

Предлагаю расширить интервал минуты.
