### ISSUE TITLE
Группа проверок на рекламные материалы

### ISSUE THREAD

**Issue by maximpashuk** [2gis/nuclear-river-validation-rules#7]
# Проверка ОДЗ для РМ (done)

Error при массовой проверке и Warning при единичной

Если для позиции заказа, такой что для любой её номенклатуры существует обязательный шаблон РМ, не существует объекта привязки с такой номенклатурой без указанного РМ, то должна выводиться ошибка:
- "В позиции `{orderPosition}` необходимо указать рекламные материалы" (**OrderCheckPositionMustHaveAdvertisements**) - для простой позиции
- "В позиции `{orderPosition}` необходимо указать рекламные материалы для подпозиции `{position}`" (**OrderCheckCompositePositionMustHaveAdvertisements**) - для сложной позиции
# Проверка ОДЗ для ЭРМ (done)

Error при массовой проверке и Warning при единичной

Если для позиции заказа такой, что для любого её РМ такого, что для любого обязательного шаблона ЭРМ найдётся незаполненный ЭРМ, то должна выводиться ошибка:
- "В рекламном материале `{advertisement}` не заполнен обязательный элемент `{advertisementElement}`" (**OrdersCheckPositionMustHaveAdvertisementElements**)

**Особенность:** Проверка не для заказа, а для РМ, нужен соответствующий агрегат

Также есть особенность с региональным заказом (см. проверку выше)
# Проверка ОДЗ для объектов привязки для сложных номенклатур

Всегда Error

Если для позиции заказа с позицией (IsComposite = true, IsCompositionOptional=false) не существует объекта привязки (на любую подпозицию), то должна выводиться ошибка:
- "В позиции `{orderPosition}` необходимо указать хотя бы один объект привязки для подпозиции `{position}`" (**OrderCheckCompositePositionMustHaveLinkingObject**)
# Проверка на неудалённый РМ (done)

Всегда Error

Если для позиции заказа существует объект привязки с удалённым РМ, то должна выводиться ошибка:
- В позиции `{orderPosition}` выбран удалённый рекламный материал `{advertisement}` (**RemovedAdvertisemendSpecifiedForPosition**)
# Проверка РМ на принадлежность фирме (done)

Всегда Error

Если для позиции заказа существует объект привязки с РМ, в РМ указана фирма и фирма заказа не содержит этот РМ, то должна выводиться ошибка:
- В позиции `{orderPosition}` выбран рекламный материал `{advertisement}`, не принадлежащий фирме `{firm}` (**AdvertisementSpecifiedForPositionDoesNotBelongToFirm**)
# Проверка ЭРМ на выверенность (done)

Error при массовой проверке и Warning при единичной

Если для позиции заказа существует РМ, такой что существует ЭРМ с шаблоном, требующим выверки, и ЭРМ имеет статус 'Выверено с ошибками', , то должна выводиться ошибка:
- В рекламном материале `{advertisement}`, который подлежит выверке, элемент `{advertisementElement}` содержит ошибки выверки (**OrdersCheckAdvertisementElementWasInvalidated**)

Если для позиции заказа существует РМ, такой что существует ЭРМ с шаблоном, требующим выверки, и ЭРМ имеет статус 'Черновик', , то должна выводиться ошибка:
- В рекламном материале `{advertisement}`, который подлежит выверке, элемент `{advertisementElement}` находится в статусе 'Черновик' (**OrdersCheckAdvertisementElementIsDraft**)
# Проверка на наличие заглушек в заказе (done)

Error если PreReleaseFinal и Warning во всех других случаях 

Если позиция заказа имеет РМ, в шаблоне которого в качестве заглушки выбран этот же РМ, то должна выводитьс ошибка: 
- Позиция `{position}` содержит заглушку рекламного материала (**OrderContainsDummyAdvertisementError**) 
# Проверка на белый список

Если набор заказов для фирмы в периоде имеют РМ, которые потенциально могут быть выбраны в белый список, и при этом число РМ, выбранных в белый список:   

равно 0 (Error если PreReleaseFinal и Warning dj всех других случаях)
- Для фирмы `{firm}` не указан рекламный материал в белый список (**AdvertisementForWhitelistDoesNotSpecified**)

равно 1 (Всегда Info)
- Для фирмы `{firm}` в белый список выбран рекламный материал `{advertisement}` (**AdvertisementChoosenForWhitelist**)

больше 1 (Всегда Error)
- Невозможнная ситуация, для фирмы `{firm}` в белый список указан более чем один рекламный материал (**MoreThanOneAdvertisementChoosenForWhitelist**)
  (**такая ситуация вообще невозможна по бузнесу, так что нет смысла её вообще реализовывать**)

**Comment by rechkalov** [comment]
#### AdvertisementsOnlyWhiteListOrderValidationRule
- Запускается во всех массовых режимах и при переводе с "на оформлении"
- Для фирм<sup>1</sup>, у которых недостаёт<sup>2</sup> выбранных в белый список РМ, должна выводиться ошибка при массовой проверке и предупреждение при единичной.
 - Для фирмы {0} не указан рекламный материал в белый список
- Для фирм<sup>1</sup>, у выбран в белый список РМ, должно выводиться информационное сообщение.
 - Для фирмы {0} в белый список выбран рекламный материал {1}

<sup>1</sup>Поскольку проверок фирм нет, то сообщения выводим в заказах этой фирмы, в которых есть как минимум один РМ с возможностью выбора в белый список.

<sup>2</sup>Значит в выпуск выходит как минимум один РМ с возможностью выбора в белый список, но ни одного выбранного.

**Comment by rechkalov** [comment]
#### AdvertisementsWithoutWhiteListOrderValidationRule (не закончено)
- Запускается во всех массовых режимах и при переводе с "на оформлении"
- Для заказов, в которых есть невыверенные<sup>1</sup> РМ должна выводиться ошибка
 - В рекламном материале "{0}", который подлежит выверке, элемент "{1}" содержит ошибки выверки
 - В рекламном материале "{0}", который подлежит выверке, элемент "{1}" находится в статусе 'Черновик'
- Для заказов, ...

<sup>1</sup>Невыверенными считаются РМ, подлежащие выверке, но находящиеся в статусе "черновик" или "содержит ошибки". Что характерно, статус "ожидает выверки" - не считается ошибочным (вероятно для выпуска РМ при большом объёме корректоров, вероятно - временное решение)

**Comment by rechkalov** [comment]
#### CouponIsUniqueForFirmOrderValidationRule
 - Запускается во всех массовых режимах и при переводе с "на оформлении"
 - Для фирм (но выводим в заказы), размещающих один РМ в более чем одной позиции "выгодные покупки", должна выводиться ошибка
 - "Купон на скидку {0} прикреплён к нескольким позициям: {1}"
 ! позиции "выгодные покупки" (CategoryCode = 14) более не продатся, нужна ли проверка?
 
#### CouponPeriodOrderValidationRule
 - Запускается во всех массовых режимах и при переводе с "на оформлении"
 - Для ЭРМ с указанными датами размещения, срок размещения не должн быть менее пяти дней, ошибка в массовой, предупреждение в единичой.
 - "Период не может быть менее пяти дней" (в единичной)
 - "Период размещения рекламного материала {0}, выбранного в позиции {1} должен захватывать 5 дней от текущего месяца размещения" (в массовой)
 * учитывается как полный срок в периоде размещения заказа, так и в каждом месяце
